destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/vegalite-pdf"
port: 4011
output: pdf
product: vegalite
print_title: Vegalite documentation
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: vegalite_sidebar
